src/Entity/Etudiant.php
<?php

namespace App\Entity;

use App\Repository\EtudiantRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=EtudiantRepository::class)
 *
 */
class Etudiant
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $matricule;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @Assert\Regex("/^7[7|8|6|0][0-9]{7}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $telephone;

    /**
     * @Assert\Regex("/^[_a-zA-Z0-9-]+(\.[_a-zA-Z0-9-]+)*@([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,4}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $date_naissance;

    /**
     * @ORM\ManyToOne(targetEntity=Chambre::class, inversedBy="etudiants")
     */
    private $chambre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricule(): ?string
    {
        return $this->matricule;
    }

    public function setMatricule(string $matricule): self
    {
        $this->matricule = $matricule;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getDateNaissance(): ?string
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(string $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): self
    {
        $this->chambre = $chambre;

        return $this;
    }
}

src/Form/EtudiantType.php
<?php

namespace App\Form;

use App\Entity\Etudiant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EtudiantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('matricule')
            ->add('nom')
            ->add('prenom')
            ->add('telephone')
            ->add('email')
            ->add('date_naissance')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Etudiant::class,
        ]);
    }
}

src/Controller/EtudiantController.php
<?php

namespace App\Controller;

use App\Entity\Etudiant;
use App\Form\Etudiant1Type;
use App\Repository\EtudiantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/etudiant")
 */
class EtudiantController extends AbstractController
{
    /**
     * @Route("/", name="etudiant_index", methods={"GET"})
     */
    public function index(EtudiantRepository $etudiantRepository): Response
    {
        return $this->render('etudiant/index.html.twig', [
            'etudiants' => $etudiantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="etudiant_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $etudiant = new Etudiant();
        $form = $this->createForm(Etudiant1Type::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($etudiant);
            $entityManager->flush();

            return $this->redirectToRoute('etudiant_index');
        }

        return $this->render('etudiant/new.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="etudiant_show", methods={"GET"})
     */
    public function show(Etudiant $etudiant): Response
    {
        return $this->render('etudiant/show.html.twig', [
            'etudiant' => $etudiant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="etudiant_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Etudiant $etudiant): Response
    {
        $form = $this->createForm(Etudiant1Type::class, $etudiant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('etudiant_index');
        }

        return $this->render('etudiant/edit.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="etudiant_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Etudiant $etudiant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etudiant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($etudiant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('etudiant_index');
    }
}

templates/etudiant/_delete_form.html.twig
<form method="post" action="{{ path('etudiant_delete', {'id': etudiant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etudiant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/etudiant/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/etudiant/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Etudiant{% endblock %}

{% block body %}
    <h1>Edit Etudiant</h1>

    {{ include('etudiant/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('etudiant_index') }}">back to list</a>

    {{ include('etudiant/_delete_form.html.twig') }}
{% endblock %}

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etudiant index{% endblock %}

{% block body %}
    <h1>Etudiant index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Matricule</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Telephone</th>
                <th>Email</th>
                <th>Date_naissance</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for etudiant in etudiants %}
            <tr>
                <td>{{ etudiant.id }}</td>
                <td>{{ etudiant.matricule }}</td>
                <td>{{ etudiant.nom }}</td>
                <td>{{ etudiant.prenom }}</td>
                <td>{{ etudiant.telephone }}</td>
                <td>{{ etudiant.email }}</td>
                <td>{{ etudiant.dateNaissance }}</td>
                <td>
                    <a href="{{ path('etudiant_show', {'id': etudiant.id}) }}">show</a>
                    <a href="{{ path('etudiant_edit', {'id': etudiant.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('etudiant_new') }}">Create new</a>
{% endblock %}

templates/etudiant/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Etudiant{% endblock %}

{% block body %}
    <h1>Create new Etudiant</h1>

    {{ include('etudiant/_form.html.twig') }}

    <a href="{{ path('etudiant_index') }}">back to list</a>
{% endblock %}

templates/etudiant/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etudiant{% endblock %}

{% block body %}
    <h1>Etudiant</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ etudiant.id }}</td>
            </tr>
            <tr>
                <th>Matricule</th>
                <td>{{ etudiant.matricule }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ etudiant.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ etudiant.prenom }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ etudiant.telephone }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ etudiant.email }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ etudiant.dateNaissance }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('etudiant_index') }}">back to list</a>

    <a href="{{ path('etudiant_edit', {'id': etudiant.id}) }}">edit</a>

    {{ include('etudiant/_delete_form.html.twig') }}
{% endblock %}